# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6e8c041cf488eb927c6c70d5b6e1b991516a2588f143cc4308c0e77edc8b99fff850813e72f3da0e26f607455a01a085efc9bcd04f0dce964ac62f027dbbfa5

test:
  secret_key_base: c7613f55d5b89b4bd11bac93ed73d62aef844c69579590a6931cbff43c805567402ba139aa5c8bdc95e671032151f66cd22db9147931906fb1fb80fefee16520

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
